export const CONFIG = {
  TILE_SIZE: 48,
  COLS: 15,
  ROWS: 11,

  BOMB_FUSE: 3.0,
  EXPLOSION_DURATION: 0.5,
  DEATH_EFFECT_DURATION: 0.8,
  RESULT_TRANSITION_DELAY: 0.9,

  INITIAL_SPAWN_INTERVAL: 2.5,
  MIN_SPAWN_INTERVAL: 0.6,
  SPAWN_INTERVAL_DECAY: 0.02,

  MAX_BOMBS_START: 2,
  MAX_BOMBS_CAP: 14,
  BOMB_INCREASE_INTERVAL: 8,

  PLAYER_RADIUS: 16,
  PLAYER_SPEED: 200,
  KNOCKBACK_DISTANCE: 48,
  STUN_DURATION: 0.75,
  KNOCKBACK_SPEED: 400,

  PLAYER_COLORS: ['#e74c3c', '#3498db', '#2ecc71', '#f39c12'],
  PLAYER_NAMES: ['Player 1', 'Player 2', 'Player 3', 'Player 4'],

  DEADZONE: 0.25,
};

export function getFieldSize() {
  return {
    width: CONFIG.COLS * CONFIG.TILE_SIZE,
    height: CONFIG.ROWS * CONFIG.TILE_SIZE,
  };
}
